pretrained_model_path: "/home/pengjie/StoryGen_c/stage1_log/_240627-104019/checkpoint_15000/" #"/home/pengjie/StoryGen_c/stage1_log/_240627-104019/checkpoint_15000/" # "./stage1_log/"
logdir: "./stage2_log/"
validation_sample_logger:
    num_inference_steps: 40
    guidance_scale: 7
gradient_accumulation_steps: 8 # yuan 8
train_steps: 50000 # yuan 50000
train_batch_size: 3 # yuan 3
validation_steps: 500
checkpointing_steps: 10000 # yuan 10000
seed: 6666
mixed_precision: 'fp16'
learning_rate: 1e-5
scale_lr: false
lr_scheduler: constant
lr_warmup_steps: 0
use_8bit_adam: true
adam_beta1: 0.9
adam_beta2: 0.999
adam_weight_decay: 0.01
adam_epsilon: 1.0e-08
max_grad_norm: 1.0
alpha: 0.3 # 0.3
# lr and gradient_accumulation_steps are changed by gpu numbers!!!